# Generated by Django 2.2.4 on 2019-08-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_view_future_post_permission'),
    ]

    operations = [
    ]
